### ISSUE TITLE
Add new Picture for Wavelab 

### ISSUE THREAD

**Issue by Wlanfr3ak** [chaos-consulting/shippics#1]
Link: https://commons.wikimedia.org/wiki/File:2023-02-22-Taufe-Wavelab.jpg
Marinetraffic: https://www.marinetraffic.com/en/ais/details/ships/shipid:7671154/mmsi:211891460/imo:0/vessel:WAVELAB
MMSI: 211891460
Rights: Its my picture and i grant the Rights for the usage in this Project for unlimited Time.

**Comment by jjx-** [comment]
Picture included
